language: node_js
node_js: stable

# S: Build LifeCycle
install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - mv CNAME ./public
  - cd ./public
  - git init
  - git config user.name "Xzzzzz"
  - git config user.email "195286381@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${blog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/195286381/195286381.github.io.git
